version: '2'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql

  fake_sqs:
    build: dockerfiles/fake_sqs
    hostname: fakesqs.localdomain
    command: /usr/local/bundle/bin/fake_sqs --bind fakesqs.localdomain

  mysql:
    image: mysql:5.7
    volumes_from:
      - storage
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  rails:
    build: dockerfiles/rails
    env_file: .docker-env
    volumes:
      - .:/usr/src/app
      - ../shoryuken:/usr/src/gem
    links:
      - fake_sqs:fakesqs.localdomain
      - mysql:mysql
    ports:
      - "3000:3000"
    command: /bin/bash

  shoryuken:
    build: dockerfiles/rails
    env_file: .docker-env
    volumes:
      - .:/usr/src/app
      - ../shoryuken:/usr/src/gem
    links:
      - fake_sqs:fakesqs.localdomain
      - mysql:mysql
    command: /bin/bash
