version: '2'
services:
  storage:
    image: busybox
    volumes:
      - /var/lib/mysql

  localsqs:
    image: localstack/localstack
    hostname: localsqs
    environment:
      SERVICES: "sqs"
      DEFAULT_REGION: "ap-northeast-1"
      DEBUG: "true"
      HOSTNAME: localsqs

  mysql:
    image: mysql:5.7
    volumes_from:
      - storage
    ports:
      - "3307:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"

  rails:
    build: dockerfiles/rails
    env_file: .docker-env
    volumes:
      - .:/usr/src/app
      - ../shoryuken:/usr/src/gem
    links:
      - localsqs:localsqs
      - mysql:mysql
    ports:
      - "3000:3000"
    command: /bin/bash

  shoryuken:
    build: dockerfiles/rails
    env_file: .docker-env
    volumes:
      - .:/usr/src/app
      - ../shoryuken:/usr/src/gem
    links:
      - localsqs:localsqs
      - mysql:mysql
    command: bundle exec shoryuken -R -C config/shoryuken.yml
